Repository FirstianB101/reciptopia-server, pull requests merged in 2022-06, with the labels that each got.

#165 AccountProfileImgService 수정
  src/main/java/kr/reciptopia/reciptopiaserver/business/service/AccountProfileImgService.java
Labels: bug, refactoring

#168 AccountProfileImg 통합 테스트 수정
  src/test/java/kr/reciptopia/reciptopiaserver/AccountProfileImgIntegrationTest.java
Labels: test, refactoring

#172 AccountProfileImgDto 수정
  src/main/java/kr/reciptopia/reciptopiaserver/business/service/AccountProfileImgService.java
  src/main/java/kr/reciptopia/reciptopiaserver/controller/AccountProfileImgController.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/AccountProfileImgDto.java
Labels: domain, refactoring

#174 AccountProfileImgImgService 수정
  src/main/java/kr/reciptopia/reciptopiaserver/business/service/AccountProfileImgService.java
Labels: enhancement, invalid, refactoring

#179 Post Like Tag 검색 API 추가
  src/docs/asciidoc/api-guide.adoc
  src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostLikeTagService.java
  src/main/java/kr/reciptopia/reciptopiaserver/business/service/searchcondition/PostLikeTagSearchCondition.java
  src/main/java/kr/reciptopia/reciptopiaserver/controller/PostLikeTagController.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/CollectorHelper.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/PostLikeTagDto.java
  src/main/java/kr/reciptopia/reciptopiaserver/persistence/repository/custom/PostLikeTagRepositoryCustom.java
  src/main/java/kr/reciptopia/reciptopiaserver/persistence/repository/implementaion/PostLikeTagRepositoryImpl.java
  src/test/java/kr/reciptopia/reciptopiaserver/PostLikeTagIntegrationTest.java
Labels: documentation, implementation, refactoring

#181 Post 조회시 Views가 올라가지 않았던 문제 수정
  src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostService.java
Labels: bug

#183 AccountProfileImgDto의 Bean Validation이 작동하지 않은 문제 해결
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/AccountProfileImgDto.java
Labels: bug, refactoring

#185 Account 통합 테스트의 테스트 케이스 이름 수정
  src/test/java/kr/reciptopia/reciptopiaserver/AccountIntegrationTest.java
Labels: test, refactoring
