Repository FirstianB101/reciptopia-server, pull requests merged in 2022-02, with the labels that each got.

#21 Comment 엔티티 추가
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/Comment.java
Labels: implementation

#23 AccountDtoMapper추가
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/mapper/AccountDtoMapper.java
Labels: implementation

#24 Reply 엔티티 추가
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/Reply.java
Labels: implementation

#38 Controller에서 Service에 값을 전달하는 방식변경
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/AccountDto.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/mapper/AccountDtoMapper.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/dto/mapper/DtoMapper.java
Labels: enhancement

#39 LikeTag 도메인 추가 및 세분화
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/Account.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/Board.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/BoardLikeTag.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/Comment.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/CommentLikeTag.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/LikeTag.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/Reply.java
  src/main/java/kr/reciptopia/reciptopiaserver/domain/model/ReplyLikeTag.java
Labels: enhancement, implementation, domain
